# Generated by Django 5.1.4 on 2024-12-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_task_date_task_task_description_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date task',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
