# Generated by Django 5.1.4 on 2024-12-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_alter_task_date_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date task',
            field=models.DateField(null=True),
        ),
    ]
