# Generated by Django 5.1.4 on 2024-12-21 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0005_alter_task_date_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date task',
            new_name='date',
        ),
    ]
